Android docs
Authing/docs pull request #30
Opened 2022-05-05 11:24 UTC by zhongjiahui

2022-05-05 11:32 UTC, willin approved these changes

2022-05-06 09:51 UTC, willin requested changes

2022-05-06 09:51 UTC, willin commented on docs/reference/sdk-for-android/social/wecom.md
> +// your_authing_app_id get from Authing console
语法和大小写

2022-05-06 13:27 UTC, willin approved these changes

2022-05-07 03:06 UTC, lancemao approved these changes

2022-05-07 03:06 UTC, merged